#!/bin/sh 
# 
# tools

mbrctl=$(which brctl)
# script to bring up the tun device in QEMU in bridged mode 
# first parameter is name of tap device (e.g. tap0)
#
# some constants specific to the local host - change to suit your host
#
ETH0IPADDR=192.168.2.1
MASK=255.255.255.0
GATEWAY=192.168.2.1
BROADCAST=192.168.2.255
#
# First take enp2s0 down, then bring it up with IP address 0.0.0.0 
#
/sbin/ifdown enp2s0
/sbin/ifconfig enp2s0 0.0.0.0 promisc up
#
# Bring up the tap device (name specified as first argument, by QEMU)
#
#/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between enp2s0 and the tap device
#
$mbrctl addbr br0
$mbrctl addif br0 enp2s0
$mbrctl addif br0 $1
# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#
$mbrctl stp br0 off 
# 
# Bring up the bridge with ETH0IPADDR and add the default route 
#
/sbin/ifconfig br0 $ETH0IPADDR netmask $MASK broadcast $BROADCAST
/sbin/route add default gw $GATEWAY
#
# stop firewall - comment this out if you don't use Firestarter
#
#/sbin/service firestarter stop 
